from __future__ import annotations

from ..reporting.variables_report import IssueKind
from ._sattline_semantic_models import SemanticRule
from ._sattline_semantic_rules_more_data import (
    CONFIG_DRIFT_RULES,
    DATAFLOW_RULES,
    FAULT_HANDLING_RULES,
    LOOP_STABILITY_RULES,
    NUMERIC_CONSTRAINT_RULES,
    SIGNAL_LIFECYCLE_RULES,
    SPEC_RULE_DESCRIPTIONS,
    TAINT_RULES,
    UNSAFE_DEFAULT_RULES,
)

VARIABLE_RULES: dict[IssueKind, SemanticRule] = {
    IssueKind.UNUSED: SemanticRule(
        id="semantic.unused-variable",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="variable",
        description="Declared variables that are never read or written.",
    ),
    IssueKind.UNUSED_DATATYPE_FIELD: SemanticRule(
        id="semantic.unused-datatype-field",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="datatype-field",
        description="Datatype fields that are never used across the analyzed target.",
    ),
    IssueKind.FIELD_READ_ONLY: SemanticRule(
        id="semantic.read-only-datatype-field",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="datatype-field",
        description="Datatype fields that are read but never written for a specific variable instance.",
    ),
    IssueKind.READ_ONLY_NON_CONST: SemanticRule(
        id="semantic.read-only-non-const",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="variable",
        description="Writable declarations that are only ever read.",
    ),
    IssueKind.NAMING_ROLE_MISMATCH: SemanticRule(
        id="semantic.naming-role-mismatch",
        source="variables",
        category="engineering-spec",
        severity="warning",
        applies_to="variable",
        description="Role-bearing variable prefixes or suffixes such as Cmd, Status, and Alarm should align with observed read and write behavior.",
    ),
    IssueKind.UI_ONLY: SemanticRule(
        id="semantic.ui-only-variable",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="variable",
        description="Variables that are only consumed through graphics or interact display wiring.",
    ),
    IssueKind.PROCEDURE_STATUS: SemanticRule(
        id="semantic.procedure-status-handling",
        source="variables",
        category="control-flow",
        severity="warning",
        applies_to="procedure-status",
        description="Procedure status outputs should be checked in control logic instead of being ignored or shown only in UI.",
    ),
    IssueKind.FIELD_NEVER_READ: SemanticRule(
        id="semantic.never-read-datatype-field",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="datatype-field",
        description="Datatype fields that are written but never subsequently read for a specific variable instance.",
    ),
    IssueKind.NEVER_READ: SemanticRule(
        id="semantic.never-read-write",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="variable",
        description="Variables that are written but never subsequently read.",
    ),
    IssueKind.WRITE_WITHOUT_EFFECT: SemanticRule(
        id="semantic.write-without-effect",
        source="variables",
        category="variable-lifecycle",
        severity="warning",
        applies_to="variable",
        description="Variables whose written values are read internally but never reach a root-visible output.",
    ),
    IssueKind.GLOBAL_SCOPE_MINIMIZATION: SemanticRule(
        id="semantic.global-scope-minimization",
        source="variables",
        category="interface-contracts",
        severity="warning",
        applies_to="global-variable",
        description="Root globals whose access never escapes a single module subtree and can be localized.",
    ),
    IssueKind.HIDDEN_GLOBAL_COUPLING: SemanticRule(
        id="semantic.hidden-global-coupling",
        source="variables",
        category="interface-contracts",
        severity="warning",
        applies_to="global-variable",
        description="Root globals that act as implicit interfaces across multiple module paths.",
    ),
    IssueKind.HIGH_FAN_IN_OUT: SemanticRule(
        id="semantic.high-fan-in-out-variable",
        source="variables",
        category="interface-contracts",
        severity="warning",
        applies_to="global-variable",
        description="Root globals that are read or written by many distinct module paths and become highly shared coordination points.",
    ),
    IssueKind.UNKNOWN_PARAMETER_TARGET: SemanticRule(
        id="semantic.unknown-parameter-target",
        source="variables",
        category="interface-contracts",
        severity="error",
        applies_to="parameter-mapping",
        description="Parameter mappings that target undeclared module parameters.",
    ),
    IssueKind.REQUIRED_PARAMETER_CONNECTION: SemanticRule(
        id="semantic.required-parameter-connection",
        source="variables",
        category="interface-contracts",
        severity="error",
        applies_to="parameter-mapping",
        description="Module instances that leave internally used moduletype parameters unmapped.",
    ),
    IssueKind.CONTRACT_MISMATCH: SemanticRule(
        id="semantic.cross-module-contract-mismatch",
        source="variables",
        category="interface-contracts",
        severity="error",
        applies_to="parameter-mapping",
        description="Parameter mappings whose connected datatypes are incompatible across module boundaries.",
    ),
    IssueKind.STRING_MAPPING_MISMATCH: SemanticRule(
        id="semantic.string-mapping-mismatch",
        source="variables",
        category="interface-contracts",
        severity="error",
        applies_to="parameter-mapping",
        description="Parameter mappings whose string-like datatypes are incompatible.",
    ),
    IssueKind.DATATYPE_DUPLICATION: SemanticRule(
        id="semantic.duplicated-datatype-layout",
        source="variables",
        category="module-structure",
        severity="warning",
        applies_to="datatype",
        description="Complex datatypes that appear duplicated by structure.",
    ),
    IssueKind.NAME_COLLISION: SemanticRule(
        id="semantic.name-collision",
        source="variables",
        category="module-structure",
        severity="warning",
        applies_to="scope",
        description="Case-insensitive declaration name collisions within a scope.",
    ),
    IssueKind.LAYOUT_OVERLAP: SemanticRule(
        id="semantic.layout-overlap",
        source="variables",
        category="module-structure",
        severity="warning",
        applies_to="layout",
        description="Sibling module invocations and rectangular graph or interact objects should not overlap in the same layout scope.",
    ),
    IssueKind.MIN_MAX_MAPPING_MISMATCH: SemanticRule(
        id="semantic.min-max-mapping-mismatch",
        source="variables",
        category="interface-contracts",
        severity="warning",
        applies_to="parameter-mapping",
        description="Min_/Max_ parameter mappings that do not line up by base name.",
    ),
    IssueKind.SHADOWING: SemanticRule(
        id="semantic.shadowing",
        source="shadowing",
        category="module-structure",
        severity="warning",
        applies_to="scope",
        description="Local declarations that shadow outer or global names.",
    ),
    IssueKind.RESET_CONTAMINATION: SemanticRule(
        id="semantic.reset-contamination",
        source="variables",
        category="control-flow",
        severity="warning",
        applies_to="sequence",
        description="Reset-state writes that are missing or incomplete across sequence flow.",
    ),
    IssueKind.IMPLICIT_LATCH: SemanticRule(
        id="semantic.implicit-latch",
        source="variables",
        category="control-flow",
        severity="warning",
        applies_to="boolean-variable",
        description="Boolean values that are set on some branches or steps without a matching False write on the complementary path.",
    ),
}

SFC_RULES: dict[str, SemanticRule] = {
    "sfc_parallel_write_race": SemanticRule(
        id="semantic.parallel-write-race",
        source="sfc",
        category="control-flow",
        severity="error",
        applies_to="sequence",
        description="Parallel SFC branches that write to the same variable or field.",
    ),
    "sfc_unreachable_sequence_node": SemanticRule(
        id="semantic.unreachable-sequence-node",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="sequence-node",
        description="Sequence nodes that cannot execute because an earlier node terminates the branch.",
    ),
    "sfc_unreachable_transition": SemanticRule(
        id="semantic.unreachable-transition",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="transition",
        description="Transitions that can never fire because an earlier node structurally terminates the branch.",
    ),
    "sfc_transition_always_true": SemanticRule(
        id="semantic.transition-always-true",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="transition",
        description="Transitions with guards that simplify to true and therefore always fire when reached.",
    ),
    "sfc_transition_always_false": SemanticRule(
        id="semantic.transition-always-false",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="transition",
        description="Transitions with guards that simplify to false and therefore can never fire.",
    ),
    "sfc_duplicate_transition_guard": SemanticRule(
        id="semantic.duplicate-transition-guard",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="transition",
        description="Transitions in the same sequence branch that normalize to the same guard logic.",
    ),
    "sfc_illegal_state_combination": SemanticRule(
        id="semantic.illegal-state-combination",
        source="sfc",
        category="control-flow",
        severity="error",
        applies_to="sequence",
        description="Configured mutually exclusive SFC steps can become active at the same time.",
    ),
    "sfc_missing_step_enter_contract": SemanticRule(
        id="semantic.missing-step-enter-contract",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="step",
        description="Configured SFC steps should initialize their required state in the enter block.",
    ),
    "sfc_missing_step_exit_contract": SemanticRule(
        id="semantic.missing-step-exit-contract",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="step",
        description="Configured SFC steps should clean up their required state in the exit block.",
    ),
    "sfc_step_state_leakage": SemanticRule(
        id="semantic.step-state-leakage",
        source="sfc",
        category="control-flow",
        severity="warning",
        applies_to="step",
        description="Configured SFC steps can inherit stale state from earlier steps when required enter writes are missing.",
    ),
}

SAME_CYCLE_RULES: dict[str, SemanticRule] = {
    "same_cycle_parallel_read_write_hazard": SemanticRule(
        id="semantic.parallel-read-write-hazard",
        source="same-cycle",
        category="control-flow",
        severity="warning",
        applies_to="sequence",
        description="Parallel SFC branches that both read and write the same variable within one scan.",
    ),
    "same_cycle_shared_access_hazard": SemanticRule(
        id="semantic.same-cycle-shared-access",
        source="same-cycle",
        category="interface-contracts",
        severity="warning",
        applies_to="variable",
        description="Shared variables that are read and written across multiple module paths within the same scan.",
    ),
}

ALARM_RULES: dict[str, SemanticRule] = {
    "alarm.duplicate_tag": SemanticRule(
        id="semantic.duplicate-alarm-tag",
        source="alarm-integrity",
        category="interface-contracts",
        severity="error",
        applies_to="alarm-source",
        description="Alarm sources should not reuse the same tag across the analyzed target.",
    ),
    "alarm.duplicate_condition": SemanticRule(
        id="semantic.duplicate-alarm-condition",
        source="alarm-integrity",
        category="control-flow",
        severity="warning",
        applies_to="alarm-source",
        description="Alarm sources should not reuse the same condition without deliberate deduplication.",
    ),
    "alarm.conflicting_priority": SemanticRule(
        id="semantic.conflicting-alarm-priority",
        source="alarm-integrity",
        category="interface-contracts",
        severity="warning",
        applies_to="alarm-source",
        description="The same alarm tag or condition should not be configured with conflicting priorities or severities.",
    ),
    "alarm.never_cleared": SemanticRule(
        id="semantic.never-cleared-alarm",
        source="alarm-integrity",
        category="control-flow",
        severity="warning",
        applies_to="alarm-variable",
        description="Alarm variables that are only forced true and never explicitly cleared can latch unexpectedly.",
    ),
}

INITIAL_VALUE_RULES: dict[str, SemanticRule] = {
    "initial-values.missing_required_default": SemanticRule(
        id="semantic.missing-parameter-initial-value",
        source="initial-values",
        category="interface-contracts",
        severity="warning",
        applies_to="parameter-module",
        description="Recipe and engineering parameter modules should resolve a startup value through a default or an explicitly initialized mapping.",
    ),
}

SAFETY_PATH_RULES: dict[str, SemanticRule] = {
    "safety-path.unconsumed_signal": SemanticRule(
        id="semantic.unconsumed-safety-signal",
        source="safety-paths",
        category="control-flow",
        severity="warning",
        applies_to="signal",
        description="Safety-critical signals that are written but never consumed across the analyzed target.",
    ),
}

TRACE_RULES: dict[str, SemanticRule] = {
    "duplicate_sibling_name": SemanticRule(
        id="semantic.duplicate-sibling-name",
        source="tracing",
        category="module-structure",
        severity="error",
        applies_to="module",
        description="Sibling modules with the same case-insensitive name.",
    ),
    "unexpected_submodule_type": SemanticRule(
        id="semantic.unexpected-submodule-type",
        source="tracing",
        category="module-structure",
        severity="error",
        applies_to="module",
        description="Unexpected non-module nodes under the submodule tree.",
    ),
}


__all__ = [
    "ALARM_RULES",
    "CONFIG_DRIFT_RULES",
    "DATAFLOW_RULES",
    "FAULT_HANDLING_RULES",
    "INITIAL_VALUE_RULES",
    "LOOP_STABILITY_RULES",
    "NUMERIC_CONSTRAINT_RULES",
    "SAFETY_PATH_RULES",
    "SFC_RULES",
    "SIGNAL_LIFECYCLE_RULES",
    "SPEC_RULE_DESCRIPTIONS",
    "TAINT_RULES",
    "TRACE_RULES",
    "UNSAFE_DEFAULT_RULES",
    "VARIABLE_RULES",
]
