# pyright: reportPrivateUsage=false
from __future__ import annotations

from types import SimpleNamespace

from sattline_parser.models.ast_model import SFCSubsequence, SFCTransition, SFCTransitionSub
from sattlint.analyzers import reset_contamination as public_reset_contamination
from sattlint.analyzers.reset_contamination._reset_latching import (
    BooleanPathState,
    all_boolean_paths_cover_false,
    boolean_path_covers_false,
    collect_boolean_seq_block_paths,
    collect_boolean_seq_node_paths,
    collect_boolean_stmt_block_paths,
    collect_boolean_stmt_paths,
    emit_branch_latch_issues,
    literal_boolean,
    merge_boolean_parallel_branch_results,
    record_boolean_assignment,
    record_boolean_function_call,
    record_boolean_write,
    scan_seq_nodes_for_latching,
    scan_stmt_block_for_latching,
    scan_stmt_for_latching,
)
from sattlint.analyzers.reset_contamination._reset_path_collection import (
    classify_reset_condition,
    clone_with_reset_state,
    collect_assignment_paths,
    collect_function_call_paths,
    collect_if_stmt_paths,
    collect_paths_from_items,
    collect_paths_in_modulecode,
    collect_seq_block_paths,
    collect_seq_node_paths,
    collect_stmt_block_paths,
    collect_stmt_paths,
    infer_alternative_states,
    is_exact_reset_condition,
    is_exact_run_condition,
    path_covers_write,
    record_function_call_writes,
    record_mode_function_call_writes,
    record_mode_write,
    record_write,
    split_var_ref,
    take_condition_branch,
    varref_casefold,
)
from sattlint.analyzers.reset_contamination._reset_path_state import (
    PathCollectionDebug,
    PathState,
    compact_path_states,
    merge_parallel_branch_results,
)

reset_analyzer = public_reset_contamination.ResetContaminationAnalyzer

reset_contamination_module = SimpleNamespace(
    SFCSubsequence=SFCSubsequence,
    SFCTransition=SFCTransition,
    SFCTransitionSub=SFCTransitionSub,
    WriteMap=public_reset_contamination.WriteMap,
    detect_implicit_latching=public_reset_contamination.detect_implicit_latching,
    detect_reset_contamination=public_reset_contamination.detect_reset_contamination,
    is_from_root_origin=public_reset_contamination.is_from_root_origin,
    _BooleanPathState=BooleanPathState,
    _PathCollectionDebug=PathCollectionDebug,
    _PathState=PathState,
    _all_boolean_paths_cover_false=all_boolean_paths_cover_false,
    _boolean_path_covers_false=boolean_path_covers_false,
    _build_local_env=reset_analyzer._build_local_env,
    _check_for_modulecode=reset_analyzer._check_for_modulecode,
    _check_for_single=reset_analyzer._check_for_single,
    _check_for_typedef=reset_analyzer._check_for_typedef,
    _classify_reset_condition=classify_reset_condition,
    _clone_with_reset_state=clone_with_reset_state,
    _collect_assignment_paths=collect_assignment_paths,
    _collect_boolean_seq_block_paths=collect_boolean_seq_block_paths,
    _collect_boolean_seq_node_paths=collect_boolean_seq_node_paths,
    _collect_boolean_stmt_block_paths=collect_boolean_stmt_block_paths,
    _collect_boolean_stmt_paths=collect_boolean_stmt_paths,
    _collect_from_module=reset_analyzer._collect_from_module,
    _collect_function_call_paths=collect_function_call_paths,
    _collect_if_stmt_paths=collect_if_stmt_paths,
    _collect_paths_from_items=collect_paths_from_items,
    _collect_paths_in_modulecode=collect_paths_in_modulecode,
    _collect_reset_old_vars=reset_analyzer._collect_reset_old_vars,
    _collect_seq_block_paths=collect_seq_block_paths,
    _collect_seq_node_paths=collect_seq_node_paths,
    _collect_stmt_block_paths=collect_stmt_block_paths,
    _collect_stmt_paths=collect_stmt_paths,
    _collect_var_refs=reset_analyzer._collect_var_refs,
    _compact_path_states=compact_path_states,
    _emit_branch_latch_issues=emit_branch_latch_issues,
    _infer_alternative_states=infer_alternative_states,
    _is_exact_reset_condition=is_exact_reset_condition,
    _is_exact_run_condition=is_exact_run_condition,
    _literal_boolean=literal_boolean,
    _merge_boolean_parallel_branch_results=merge_boolean_parallel_branch_results,
    _merge_parallel_branch_results=merge_parallel_branch_results,
    _path_covers_write=path_covers_write,
    _record_boolean_assignment=record_boolean_assignment,
    _record_boolean_function_call=record_boolean_function_call,
    _record_boolean_write=record_boolean_write,
    _record_function_call_writes=record_function_call_writes,
    _record_mode_function_call_writes=record_mode_function_call_writes,
    _record_mode_write=record_mode_write,
    _record_write=record_write,
    _scan_seq_nodes_for_latching=scan_seq_nodes_for_latching,
    _scan_stmt_block_for_latching=scan_stmt_block_for_latching,
    _scan_stmt_for_latching=scan_stmt_for_latching,
    _should_analyze_path=reset_analyzer._should_analyze_path,
    _split_var_ref=split_var_ref,
    _take_condition_branch=take_condition_branch,
    _varref_casefold=varref_casefold,
)

__all__ = ["reset_contamination_module"]
