# ruff: noqa: F401, F403
from tests._analyzers_variables_adjacent_analyzers import (
    test_cyclomatic_complexity_flags_high_complexity_program_modulecode,
    test_cyclomatic_complexity_flags_high_complexity_sfc_step,
    test_cyclomatic_complexity_ignores_low_complexity_program_modulecode,
    test_loop_output_refactor_detects_cycle_across_equations_and_active_step,
    test_loop_output_refactor_ignores_acyclic_sorted_blocks,
    test_mms_interface_collects_nested_typedef_mappings_and_write_locations,
    test_mms_interface_flags_dead_tags_for_unwritten_outgoing_variables,
    test_mms_interface_flags_duplicate_tags_and_datatype_mismatch_from_icf_entries,
    test_mms_interface_flags_naming_drift_from_icf_entries,
    test_mms_interface_uses_moduletype_default_tags_for_duplicate_and_dead_tag_checks,
    test_parameter_drift_flags_diverging_literal_parameter_values,
    test_parameter_drift_ignores_aligned_literal_parameter_values,
    test_scan_loop_resource_usage_flags_non_precision_builtin_in_active_step_code,
    test_scan_loop_resource_usage_flags_non_precision_builtin_in_equation_block,
    test_scan_loop_resource_usage_ignores_non_precision_builtin_outside_active_scan_context,
)

from ._analyzers_variables_part1 import *
from ._analyzers_variables_part2 import *
from ._analyzers_variables_part3 import *
from ._analyzers_variables_part4 import *
from ._analyzers_variables_part5 import *
