from __future__ import annotations

from tests import test_repo_audit as repo_audit_tests


def test_doc_gardener_flags_markdown_mojibake(tmp_path):
    repo_audit_tests.test_doc_gardener_flags_markdown_mojibake(tmp_path)


def test_doc_gardener_scan_agents_md_reports_missing_and_structure_findings(tmp_path):
    repo_audit_tests.test_doc_gardener_scan_agents_md_reports_missing_and_structure_findings(tmp_path)


def test_doc_gardener_scan_dead_links_and_structure_findings(tmp_path):
    repo_audit_tests.test_doc_gardener_scan_dead_links_and_structure_findings(tmp_path)


def test_doc_gardener_scan_ai_first_source_drift_reports_missing_ledger_section(tmp_path):
    repo_audit_tests.test_doc_gardener_scan_ai_first_source_drift_reports_missing_ledger_section(tmp_path)


def test_doc_gardener_scan_ai_first_status_drift_reports_mismatch(tmp_path):
    repo_audit_tests.test_doc_gardener_scan_ai_first_status_drift_reports_mismatch(tmp_path)


def test_doc_gardener_run_scan_aggregates_findings(monkeypatch):
    repo_audit_tests.test_doc_gardener_run_scan_aggregates_findings(monkeypatch)


def test_doc_gardener_main_reports_findings_without_opening_pr_by_default(monkeypatch, capsys):
    repo_audit_tests.test_doc_gardener_main_reports_findings_without_opening_pr_by_default(monkeypatch, capsys)


def test_run_harness_freshness_check_translates_ai_and_doc_findings(monkeypatch, tmp_path):
    repo_audit_tests.test_run_harness_freshness_check_translates_ai_and_doc_findings(monkeypatch, tmp_path)
