# pyright: reportUnknownMemberType=false, reportUnknownParameterType=false, reportMissingParameterType=false, reportUnknownArgumentType=false
from __future__ import annotations

from tests import test_ai_work_map_freshness as ai_work_map_freshness_tests


def test_verify_ai_harness_freshness_reports_generated_map_and_metadata_drift(tmp_path):
    ai_work_map_freshness_tests.test_verify_ai_harness_freshness_reports_generated_map_and_metadata_drift(tmp_path)


def test_verify_ai_harness_freshness_passes_for_live_metadata(tmp_path):
    ai_work_map_freshness_tests.test_verify_ai_harness_freshness_passes_for_live_metadata(tmp_path)
