from __future__ import annotations

from ._builtin_datatypes_shared import BOOL as _BOOL
from ._builtin_datatypes_shared import INT as _INT
from ._builtin_datatypes_shared import REAL as _REAL
from ._builtin_datatypes_shared import BuiltinFieldSpec

BUILTIN_RECORD_SPECS_PART3: dict[str, tuple[BuiltinFieldSpec, ...]] = {
    "BooleanSignal": (
        ("Value", _BOOL),
        ("IoValue", _BOOL),
        ("Forced", _BOOL),
    ),
    "IntegerSignal": (
        ("Value", _INT),
        ("IoValue", _INT),
        ("Forced", _BOOL),
    ),
    "AnalogSignalIn": (
        ("Value", _REAL),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("Inverted", _BOOL),
        ("Parameters", "SignalPar"),
    ),
    "AnalogSignalOut": (
        ("Value", _REAL),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("Inverted", _BOOL),
        ("Parameters", "SignalPar"),
        ("ValueBack", _REAL),
        ("ManualBack", _BOOL),
    ),
    "CounterSignal": (
        ("Value", _REAL),
        ("UnscaledIoValue", _INT),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("PulsesPerUnit", _REAL),
        ("Offset", _REAL),
        ("ResetToOffset", _BOOL),
        ("Parameters", "SignalPar"),
        ("LatchValue", _INT),
        ("ControlReadBack", _INT),
        ("PresetValue", _INT),
        ("Signals", _INT),
        ("Control", _INT),
        ("Preset", _BOOL),
        ("PresetEnable", _BOOL),
        ("CounterEnable", _BOOL),
        ("CalEnable", _BOOL),
        ("CalDirection", _BOOL),
        ("CalReset", _BOOL),
        ("RangeLimited", _BOOL),
        ("LatchedReset", _BOOL),
        ("PresetReset", _BOOL),
        ("A", _BOOL),
        ("B", _BOOL),
        ("Z", _BOOL),
        ("G", _BOOL),
        ("Calibrated", _BOOL),
        ("Latched", _BOOL),
        ("PresetReached", _BOOL),
    ),
    "IP4Signal": (
        ("Value", _REAL),
        ("UnscaledIoValue", _INT),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("PulsesPerUnit", _REAL),
        ("Offset", _REAL),
        ("ResetToOffset", _BOOL),
        ("Parameters", "SignalPar"),
        ("LatchValue", _INT),
        ("ControlReadBack", _INT),
        ("PresetValue", _INT),
        ("Signals", _INT),
        ("Control", _INT),
        ("Preset", _BOOL),
        ("PresetEnable", _BOOL),
        ("CounterEnable", _BOOL),
        ("CalEnable", _BOOL),
        ("CalDirection", _BOOL),
        ("CalReset", _BOOL),
        ("RangeLimited", _BOOL),
        ("LatchedReset", _BOOL),
        ("PresetReset", _BOOL),
        ("A", _BOOL),
        ("B", _BOOL),
        ("Z", _BOOL),
        ("G", _BOOL),
        ("Calibrated", _BOOL),
        ("Latched", _BOOL),
        ("PresetReached", _BOOL),
    ),
}
