"""Builtin structured datatype catalog for system and library datatypes."""

from __future__ import annotations

from sattline_parser.models.ast_model import Simple_DataType

BuiltinFieldSpec = tuple[str, Simple_DataType | str]

_BOOL = Simple_DataType.BOOLEAN
_INT = Simple_DataType.INTEGER
_REAL = Simple_DataType.REAL
_STR = Simple_DataType.STRING
_IDENT = Simple_DataType.IDENTSTRING
_TAG = Simple_DataType.TAGSTRING
_LINE = Simple_DataType.LINESTRING
_MAX = Simple_DataType.MAXSTRING
_TIME = Simple_DataType.TIME
_DURATION = Simple_DataType.DURATION


def _status_text_group(index: int) -> tuple[BuiltinFieldSpec, ...]:
    return (
        (f"OnText{index}", _IDENT),
        (f"OffText{index}", _IDENT),
        (f"Acktext{index}", _IDENT),
        (f"InhibitText{index}", _IDENT),
        (f"InhibitCancelText{index}", _IDENT),
        (f"AutoBlockText{index}", _IDENT),
    )


_SELECT_CLASS_USER_FIELDS = tuple(
    field
    for index in range(1, 11)
    for field in (
        (f"UserClass{index}", _INT),
        (f"UserTimeOut{index}", _INT),
    )
)

_STATUS_TEXT_FIELDS = (
    ("LostStateText", _IDENT),
    *_status_text_group(1),
    *_status_text_group(2),
    *_status_text_group(3),
)

_AXIS_FIELDS = tuple(
    (name, _REAL)
    for name in (
        "Xmin",
        "X1number",
        "X1interval",
        "X2number",
        "X2interval",
        "X3number",
        "X3interval",
        "X4number",
        "X4interval",
        "X5number",
        "X5interval",
        "Ymin",
        "Y1number",
        "Y1interval",
        "Y2number",
        "Y2interval",
        "Y3number",
        "Y3interval",
        "Y4number",
        "Y4interval",
        "Y5number",
        "Y5interval",
    )
)

_CURVE_MASTER_FIELDS = tuple((f"x{x}y{y}", _REAL) for y in range(3) for x in range(5))

_STATIC_FUNCTION_POINT_FIELDS = tuple((f"{axis}{index}", _REAL) for index in range(3, 11) for axis in ("x", "y"))

_STATIC_FUNCTION_USED_FIELDS = tuple((f"x{index}used", _BOOL) for index in range(3, 11))

_MANUAL_AUTO_REAL_FIELDS = (
    ("ManualValue", _REAL),
    ("Automatic", _BOOL),
    ("Max", _REAL),
    ("Min", _REAL),
)

_OPAQUE_BUILTIN_RECORD_NAMES = (
    "AcofTimerType",
    "ArrayObject",
    "EventQueueItem",
    "EventSortRecType",
    "QueueObject",
    "RandomGenerator",
    "SortedEventType",
    "Timer",
    "tObject",
)


BUILTIN_RECORD_SPECS: dict[str, tuple[BuiltinFieldSpec, ...]] = {
    "AcofType": (
        ("TimeOut", _BOOL),
        ("OO_old", _BOOL),
        ("OC_old", _BOOL),
        ("Answer", _BOOL),
        ("Elapsed", Simple_DataType.DURATION),
        ("AcofTimer", "AcofTimerType"),
    ),
    "AsyncOperation": (("Status", _INT),),
    "DurationRecord": (
        ("Days", _INT),
        ("Hours", _INT),
        ("Minutes", _INT),
        ("Seconds", _INT),
        ("MilliSeconds", _INT),
    ),
    "TimeRecord": (
        ("Year", _INT),
        ("Month", _INT),
        ("Day", _INT),
        ("Hour", _INT),
        ("Minute", _INT),
        ("Second", _INT),
        ("MilliSecond", _INT),
    ),
    "CalendarRecord": (
        ("Year", _INT),
        ("Month", _INT),
        ("Day", _INT),
        ("WeekDay", _INT),
    ),
    "GroupData": (("WarmStarting", _BOOL),),
    "TimeFormatType": (
        ("ShortTime", _STR),
        ("MinAndSec", _STR),
        ("Sec", _STR),
        ("DateAndTime", _STR),
        ("Date", _STR),
        ("Time", _STR),
        ("ShortDate", _STR),
        ("EventTime", _STR),
        ("UserTime", _STR),
    ),
    "ColoursType": (
        ("WarningColour", _INT),
        ("ErrorColour", _INT),
        ("OkColour", _INT),
        ("PvColour", _INT),
        ("SpColour", _INT),
        ("OutColour", _INT),
        ("PresColour", _INT),
        ("AlarmHLColour", _INT),
        ("AlarmHHLLColour", _INT),
        ("RelAlarmColour", _INT),
        ("ManualColour", _INT),
        ("Curve1", _INT),
        ("Curve2", _INT),
        ("Curve3", _INT),
        ("Curve4", _INT),
        ("EventOnColour", _INT),
        ("EventOffColour", _INT),
        ("EventAckColour", _INT),
        ("OnColour", _INT),
        ("OffColour", _INT),
        ("IconFrameColour", _INT),
        ("FaultColour", _INT),
        ("ForcedBackColour", _INT),
        ("ForcedColour", _INT),
        ("ObjectOffColour", _INT),
        ("UserColour3", _INT),
        ("UserColour4", _INT),
        ("UserColour5", _INT),
        ("UserColour6", _INT),
    ),
    "SelectClassType": (
        ("Class1", _INT),
        ("TimeOut1", _INT),
        ("Class2", _INT),
        ("TimeOut2", _INT),
        ("Class3", _INT),
        ("TimeOut3", _INT),
        *_SELECT_CLASS_USER_FIELDS,
    ),
    "StatusTextsType": _STATUS_TEXT_FIELDS,
    "PresFormatsType": (
        ("EventList", _STR),
        ("EventLogPrin", _STR),
        ("EventLogPrint", _STR),
        ("EventPrintShort", _STR),
        ("OpBoolLogPrint", _STR),
        ("OpIntLogPrint", _STR),
        ("OpRealLogPrint", _STR),
        ("OpStringLogPrint", _STR),
        ("OpBoolPrintShort", _STR),
        ("OpIntPrintShort", _STR),
        ("OpRealPrintShort", _STR),
        ("OpStringPrintShort", _STR),
    ),
    "ProgStationData": (
        ("GroupProg", "GroupData"),
        ("GroupProgFast", "GroupData"),
        ("SelectClass", "SelectClassType"),
        ("Path", _IDENT),
        ("MinusOneInteger", _INT),
        ("ZeroInteger", _INT),
        ("Status", _INT),
        ("Reserved", _INT),
        ("IdentifierProg", _INT),
        ("RutiListObject", "tObject"),
        ("Colours", "ColoursType"),
        ("TimeFormats", "TimeFormatType"),
        ("PresentationFormats", "PresFormatsType"),
        ("StatusTexts", "StatusTextsType"),
        ("CurveRealSData", "CurveRealSData"),
    ),
    "InitVariableType": (
        ("B", _BOOL),
        ("I", _INT),
        ("R", _REAL),
        ("S", _STR),
    ),
    "ModulePar": (
        ("Par1", _INT),
        ("Par2", _INT),
        ("Par3", _INT),
    ),
    "OnOffTimerType": (
        ("Hold", _BOOL),
        ("Elapsed", Simple_DataType.DURATION),
        ("Timer", "Timer"),
    ),
    "ScanGroupControlPar": (
        ("RequestedCycleTime", _INT),
        ("Priority", _INT),
        ("Phase", _INT),
        ("CyclicExecution", _BOOL),
        ("ExecuteOneScan", _BOOL),
    ),
    "ScanGroupExtPar": (("CycleTimeFactor", _INT),),
    "FBReadPar": (("Period", _INT),),
    "Alarm4Par": (
        ("HHrelative", _REAL),
        ("Hrelative", _REAL),
        ("Lrelative", _REAL),
        ("LLrelative", _REAL),
        ("Level1Alarm", _BOOL),
        ("Level2Alarm", _BOOL),
    ),
    "Alarm4RealSPar": (
        ("HHlimit", _REAL),
        ("Hlimit", _REAL),
        ("Llimit", _REAL),
        ("LLlimit", _REAL),
        ("Hysteresis", _REAL),
        ("TimeDelay", _INT),
    ),
    "AdaptivePidPar": (
        ("Gain", _REAL),
        ("Gain2", _REAL),
        ("Gain3", _REAL),
        ("Gain4", _REAL),
        ("Ti", _REAL),
        ("Ti2", _REAL),
        ("Ti3", _REAL),
        ("Ti4", _REAL),
        ("Td", _REAL),
        ("Td2", _REAL),
        ("Td3", _REAL),
        ("Td4", _REAL),
        ("Lim1", _REAL),
        ("Lim2", _REAL),
        ("Lim3", _REAL),
        ("DeadTime", _REAL),
        ("Bias", _REAL),
        ("Dz", _REAL),
        ("Direct", _BOOL),
        ("Integral", _BOOL),
        ("FeedForwardGain", _REAL),
        ("SpMax", _REAL),
        ("SpMin", _REAL),
        ("LimitOutput", _BOOL),
        ("CMaxLimit", _REAL),
        ("CMinLimit", _REAL),
        ("CIncSpeed", _REAL),
        ("CDecSpeed", _REAL),
        ("SpManualValue", _REAL),
        ("External", _BOOL),
        ("CManualValue", _REAL),
        ("Automatic", _BOOL),
        ("Tune", _BOOL),
        ("DirectKnown", _BOOL),
        ("Reset", _BOOL),
        ("MaxRelay", _REAL),
        ("RegDes", _INT),
        ("RegDesSpeed", _INT),
        ("DesignIsNormal", _BOOL),
        ("DesignIsPI", _BOOL),
        ("DesignIsDeadtime", _BOOL),
        ("DesignSpeedNormal", _BOOL),
        ("DesignSpeedFast", _BOOL),
        ("DesignSpeedSlow", _BOOL),
        ("ReDesign", _BOOL),
        ("Message", _INT),
        ("GSref", _REAL),
        ("GSvariable", _INT),
        ("GSrefIsC", _BOOL),
        ("GSrefIsPv", _BOOL),
        ("GSrefIsSp", _BOOL),
        ("GSrefIsExt", _BOOL),
        ("Set1", _BOOL),
        ("Set2", _BOOL),
        ("Set3", _BOOL),
        ("Set4", _BOOL),
        ("UseSet2", _BOOL),
        ("UseSet3", _BOOL),
        ("UseSet4", _BOOL),
        ("TunerGain", _REAL),
        ("TunerTi", _REAL),
        ("TunerTd", _REAL),
        ("TunerPidParValid", _BOOL),
        ("LoadTunerPar", _BOOL),
        ("NotLoadTunerPar", _BOOL),
        ("MaxSamp", _REAL),
        ("MaxSampValid", _BOOL),
        ("AdaptMessage", _INT),
        ("EnableFBAdaption", _BOOL),
        ("ResetFBAdapt", _BOOL),
        ("FBAdaptActive", _BOOL),
        ("EnableFFAdaption", _BOOL),
        ("ResetFFAdapt", _BOOL),
        ("FFAdaptActive", _BOOL),
        ("RegDes1", _INT),
        ("RegDes2", _INT),
        ("RegDes3", _INT),
        ("RegDes4", _INT),
        ("RegDesSpeed1", _INT),
        ("RegDesSpeed2", _INT),
        ("RegDesSpeed3", _INT),
        ("RegDesSpeed4", _INT),
        ("OscillationDetection", _BOOL),
        ("SluggishDetection", _BOOL),
        ("DirectionUp", _INT),
        ("RampAmplitude", _REAL),
        ("RampDuration", _DURATION),
        ("InitialDelay", _DURATION),
        ("RampStepwise", _BOOL),
        ("RampNoOfSteps", _INT),
        ("LimitPv", _BOOL),
        ("MaxPvChange", _REAL),
        ("StepAmplitude", _REAL),
        ("StepDuration", _DURATION),
        ("StepAlternating", _BOOL),
        ("HystFricAmplitude", _REAL),
        ("HystFricDuration", _DURATION),
        ("RampActive", _BOOL),
        ("StepActive", _BOOL),
        ("HystFricActive", _BOOL),
        ("StopExperiment", _BOOL),
    ),
    "AddRealSPar": (
        ("Gain", _REAL),
        ("Bias", _REAL),
    ),
    "Axis": _AXIS_FIELDS,
    "SignalPar": (
        ("Max", _REAL),
        ("Min", _REAL),
        ("Unit", _IDENT),
        ("Fraction", _INT),
    ),
    "ChangeRateLimRSPar": (
        ("Dmax", _REAL),
        ("Dmin", _REAL),
    ),
    "CommonRangeRealSPar": (
        ("Out1Part", _REAL),
        ("Dummy1", _BOOL),
    ),
    "CounterInRealSPar": (
        ("CUnit", _STR),
        ("ResetCounter", _BOOL),
        ("ResetValue", _REAL),
        ("ManualValue", _REAL),
        ("Automatic", _BOOL),
        ("Counter16Bit", _BOOL),
        ("PulsesPerUnit", _REAL),
        ("SelectModel", _BOOL),
    ),
    "CurveMaster": (
        *_AXIS_FIELDS,
        *_CURVE_MASTER_FIELDS,
    ),
    "DigitalOutRealSPar": (
        ("ManualValue", _REAL),
        ("Automatic", _BOOL),
        ("MinMaxTime", _REAL),
        ("Deadzone", _REAL),
        ("DelayIncDec", _REAL),
    ),
    "DifferentiatorRSPar": (
        ("Time", _REAL),
        ("Gain", _REAL),
        ("Dz", _REAL),
    ),
    "EstState": (
        ("b1", _REAL),
        ("b2", _REAL),
        ("f1", _REAL),
        ("f2", _REAL),
        ("scale", _REAL),
    ),
    "FFEstState": (
        ("a", _REAL),
        ("b", _REAL),
        ("f1", _REAL),
        ("f2", _REAL),
        ("p11", _REAL),
        ("p22", _REAL),
    ),
    "FilterRealSPar": (
        ("Time", _REAL),
        ("Dummy1", _BOOL),
    ),
    "FiltPar": (
        ("a1", _REAL),
        ("a2", _REAL),
        ("b1", _REAL),
        ("b2", _REAL),
        ("norm", _REAL),
    ),
    "FiltState": (
        ("Out", _REAL),
        ("x1", _REAL),
        ("x2", _REAL),
    ),
    "FrequencyInRealSPar": (
        ("CUnit", _STR),
        ("ManualValue", _REAL),
        ("Automatic", _BOOL),
        ("Counter16Bit", _BOOL),
        ("PulsesPerSec", _REAL),
        ("SelectModel", _BOOL),
    ),
    "IntegratorRealSPar": (
        ("Gain", _REAL),
        ("Bias", _REAL),
        ("Max", _REAL),
        ("Min", _REAL),
    ),
    "LimiterRealSPar": (
        ("Max", _REAL),
        ("Min", _REAL),
    ),
    "ManualAutoRealSPar": _MANUAL_AUTO_REAL_FIELDS,
    "MassFlowRealSPar": (
        ("ManualValue", _REAL),
        ("Automatic", _BOOL),
        ("Pa", _REAL),
        ("Pb", _REAL),
        ("Tb", _REAL),
    ),
    "MaxMinRealSPar": (
        ("ToleranceOutIn1", _REAL),
        ("ToleranceOutIn2", _REAL),
    ),
    "MultRealSPar": (
        ("Gain", _REAL),
        ("Bias", _REAL),
    ),
    "PidPar": (
        ("Gain", _REAL),
        ("Ti", _REAL),
        ("Td", _REAL),
        ("Tfil", _REAL),
        ("Bias", _REAL),
        ("Dz", _REAL),
        ("Direct", _BOOL),
        ("Integral", _BOOL),
        ("FeedForwardGain", _REAL),
        ("DeadTime", _REAL),
        ("LimitOutput", _BOOL),
        ("CMaxLimit", _REAL),
        ("CMinLimit", _REAL),
        ("CIncSpeed", _REAL),
        ("CDecSpeed", _REAL),
        ("SpManualValue", _REAL),
        ("External", _BOOL),
        ("CManualValue", _REAL),
        ("Automatic", _BOOL),
        ("OscillationDetection", _BOOL),
    ),
    "RealSignal": (
        ("Value", _REAL),
        ("Valid", _BOOL),
        ("Forced", _BOOL),
        ("ForcedBack", _BOOL),
        ("ValueBack", _REAL),
    ),
    "RealSignalBack": (
        ("ForcedBack", _BOOL),
        ("ValueBack", _REAL),
    ),
    "RealSignalForward": (
        ("Value", _REAL),
        ("Valid", _BOOL),
        ("Forced", _BOOL),
    ),
    "RealSToRealPar": _MANUAL_AUTO_REAL_FIELDS,
    "RealToRealSPar": _MANUAL_AUTO_REAL_FIELDS,
    "RelativeAlarm2Par": (
        ("Hlimit", _REAL),
        ("Llimit", _REAL),
        ("Hysteresis", _REAL),
        ("TimeDelay", _INT),
        ("StartDelay", _INT),
    ),
    "RelAlarm2Connection": (
        ("Reference", _REAL),
        ("Value", _REAL),
        ("Valid", _BOOL),
        ("Hrelative", _REAL),
        ("Lrelative", _REAL),
        ("Level1Alarm", _BOOL),
    ),
    "RelayPidTunerPar": (
        ("Gain", _REAL),
        ("Gain2", _REAL),
        ("Gain3", _REAL),
        ("Gain4", _REAL),
        ("Ti", _REAL),
        ("Ti2", _REAL),
        ("Ti3", _REAL),
        ("Ti4", _REAL),
        ("Td", _REAL),
        ("Td2", _REAL),
        ("Td3", _REAL),
        ("Td4", _REAL),
        ("Lim1", _REAL),
        ("Lim2", _REAL),
        ("Lim3", _REAL),
        ("DeadTime", _REAL),
        ("Bias", _REAL),
        ("Dz", _REAL),
        ("Direct", _BOOL),
        ("Integral", _BOOL),
        ("FeedForwardGain", _REAL),
        ("SpMax", _REAL),
        ("SpMin", _REAL),
        ("LimitOutput", _BOOL),
        ("CMaxLimit", _REAL),
        ("CMinLimit", _REAL),
        ("CIncSpeed", _REAL),
        ("CDecSpeed", _REAL),
        ("SpManualValue", _REAL),
        ("External", _BOOL),
        ("CManualValue", _REAL),
        ("Automatic", _BOOL),
        ("Tune", _BOOL),
        ("DirectKnown", _BOOL),
        ("Reset", _BOOL),
        ("MaxRelay", _REAL),
        ("RegDes", _INT),
        ("RegDesSpeed", _INT),
        ("DesignIsNormal", _BOOL),
        ("DesignIsPI", _BOOL),
        ("DesignIsDeadtime", _BOOL),
        ("DesignSpeedNormal", _BOOL),
        ("DesignSpeedFast", _BOOL),
        ("DesignSpeedSlow", _BOOL),
        ("ReDesign", _BOOL),
        ("Message", _INT),
        ("GSref", _REAL),
        ("GSvariable", _INT),
        ("GSrefIsC", _BOOL),
        ("GSrefIsPv", _BOOL),
        ("GSrefIsSp", _BOOL),
        ("GSrefIsExt", _BOOL),
        ("Set1", _BOOL),
        ("Set2", _BOOL),
        ("Set3", _BOOL),
        ("Set4", _BOOL),
        ("UseSet2", _BOOL),
        ("UseSet3", _BOOL),
        ("UseSet4", _BOOL),
        ("TunerGain", _REAL),
        ("TunerTi", _REAL),
        ("TunerTd", _REAL),
        ("TunerPidParValid", _BOOL),
        ("LoadTunerPar", _BOOL),
        ("NotLoadTunerPar", _BOOL),
        ("MaxSamp", _REAL),
        ("MaxSampValid", _BOOL),
        ("OscillationDetection", _BOOL),
    ),
    "SAPar": (
        ("Enable_Analyze", _BOOL),
        ("Reset", _BOOL),
        ("Freq1", _REAL),
        ("Freq2", _REAL),
        ("Freq3", _REAL),
        ("Freq4", _REAL),
        ("Freq5", _REAL),
        ("Freq6", _REAL),
        ("Freq7", _REAL),
        ("MaxEnergy", _REAL),
        ("MaxFreq", _REAL),
        ("HalfFreq", _REAL),
        ("IncFreq", _BOOL),
        ("DecFreq", _BOOL),
        ("FreqFactor", _INT),
        ("AdaptRate", _INT),
        ("Filt_TimeConstant", _REAL),
        ("Filt_Percentage", _REAL),
        ("Filt_FreqMin", _REAL),
        ("Filt_DisplayInfo", _BOOL),
        ("TotalTime", _REAL),
        ("ElapsedTime", _REAL),
        ("Warning", _BOOL),
        ("Signal_StandDev", _REAL),
        ("StartOnManualChange", _BOOL),
        ("StopOnStationary", _BOOL),
        ("WindowDisplayed", _BOOL),
        ("TimeElapsed", _STR),
        ("Time", _DURATION),
    ),
    "SelectorChain": (
        ("Number", _INT),
        ("ProposedNb", _INT),
        ("SelectedNb", _INT),
        ("Signal", "RealSignal"),
    ),
    "SplitRangeRealSPar": (
        ("imin1", _REAL),
        ("imax1", _REAL),
        ("omin1", _REAL),
        ("omax1", _REAL),
        ("imin2", _REAL),
        ("imax2", _REAL),
        ("omin2", _REAL),
        ("omax2", _REAL),
    ),
    "SqrtRealSPar": (
        ("Gain", _REAL),
        ("Bias", _REAL),
        ("Linear", _REAL),
    ),
    "StaticFunctionRSPar": (
        ("Bias", _REAL),
        ("x1", _REAL),
        ("y1", _REAL),
        ("x2", _REAL),
        ("y2", _REAL),
        *_STATIC_FUNCTION_POINT_FIELDS,
        *_STATIC_FUNCTION_USED_FIELDS,
    ),
    "StictionCompRealSPar": (
        ("EnableStictionComp", _BOOL),
        ("PulseAmplitude", _REAL),
        ("PulseWidth", _REAL),
        ("PulsePeriodFactor", _INT),
    ),
    "TestPar": (
        ("Step_Prompt", _BOOL),
        ("Step_PosAnswer", _BOOL),
        ("Step_NegAnswer", _BOOL),
        ("HystFric_Prompt", _BOOL),
        ("HystFric_PosAnswer", _BOOL),
        ("HystFric_NegAnswer", _BOOL),
        ("FrictionAccuracy", _INT),
        ("Ramp_Back", _BOOL),
        ("PvMax", _REAL),
        ("PvMin", _REAL),
        ("ElapsedTime", _REAL),
        ("TotalTime", _REAL),
        ("DeadTime", _REAL),
        ("StaticGain", _REAL),
        ("TimeConstant", _REAL),
        ("Friction", _REAL),
        ("Hysteresis", _REAL),
        ("TestInProgress", _BOOL),
        ("Status", _INT),
        ("Warning", _INT),
        ("ForcedBack", _BOOL),
        ("DurationChanged", _BOOL),
    ),
    "EventConnection": (
        ("Condition", _BOOL),
        ("Status", _INT),
    ),
    "LoggedEvent": (
        ("FormattedInfo", _MAX),
        ("Id", "LoggedEventKey"),
        ("Description", _LINE),
        ("Data", _LINE),
        ("DataOld", _LINE),
    ),
    "LoggedEventKey": (
        ("objecttag", _TAG),
        ("user", _IDENT),
        ("severity", _INT),
        ("class", _INT),
        ("alon", _BOOL),
        ("aloff", _BOOL),
        ("ack", _BOOL),
        ("inh", _BOOL),
        ("caninh", _BOOL),
        ("autoinh", _BOOL),
        ("autoinhoff", _BOOL),
        ("opinteract", _BOOL),
    ),
    "CurveRealSData": (
        ("PathSuffix", _STR),
        ("PathPrefix", _STR),
    ),
    "JournalAttributes": (
        ("deletable", _BOOL),
        ("overwrite", _BOOL),
        ("autonewentry", _BOOL),
    ),
    "ComliAlarmTxtType": (
        ("Status", _INT),
        ("IOAddress", _INT),
        ("AckAddress", _INT),
        ("Time", _TIME),
        ("AlarmText", _LINE),
    ),
    "ComliAlarmackType": (
        ("IOAddress", _INT),
        ("AckAddress", _INT),
    ),
    "VarGroupType": (
        ("GroupRef", "tObject"),
        ("RemoteError", _BOOL),
        ("GroupIsDefined", _BOOL),
    ),
    "BooleanSignal": (
        ("Value", _BOOL),
        ("IoValue", _BOOL),
        ("Forced", _BOOL),
    ),
    "IntegerSignal": (
        ("Value", _INT),
        ("IoValue", _INT),
        ("Forced", _BOOL),
    ),
    "AnalogSignalIn": (
        ("Value", _REAL),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("Inverted", _BOOL),
        ("Parameters", "SignalPar"),
    ),
    "AnalogSignalOut": (
        ("Value", _REAL),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("Inverted", _BOOL),
        ("Parameters", "SignalPar"),
        ("ValueBack", _REAL),
        ("ManualBack", _BOOL),
    ),
    "CounterSignal": (
        ("Value", _REAL),
        ("UnscaledIoValue", _INT),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("PulsesPerUnit", _REAL),
        ("Offset", _REAL),
        ("ResetToOffset", _BOOL),
        ("Parameters", "SignalPar"),
        ("LatchValue", _INT),
        ("ControlReadBack", _INT),
        ("PresetValue", _INT),
        ("Signals", _INT),
        ("Control", _INT),
        ("Preset", _BOOL),
        ("PresetEnable", _BOOL),
        ("CounterEnable", _BOOL),
        ("CalEnable", _BOOL),
        ("CalDirection", _BOOL),
        ("CalReset", _BOOL),
        ("RangeLimited", _BOOL),
        ("LatchedReset", _BOOL),
        ("PresetReset", _BOOL),
        ("A", _BOOL),
        ("B", _BOOL),
        ("Z", _BOOL),
        ("G", _BOOL),
        ("Calibrated", _BOOL),
        ("Latched", _BOOL),
        ("PresetReached", _BOOL),
    ),
    "IP4Signal": (
        ("Value", _REAL),
        ("UnscaledIoValue", _INT),
        ("ScaledIoValue", _REAL),
        ("Valid", _INT),
        ("Forced", _BOOL),
        ("PulsesPerUnit", _REAL),
        ("Offset", _REAL),
        ("ResetToOffset", _BOOL),
        ("Parameters", "SignalPar"),
        ("LatchValue", _INT),
        ("ControlReadBack", _INT),
        ("PresetValue", _INT),
        ("Signals", _INT),
        ("Control", _INT),
        ("Preset", _BOOL),
        ("PresetEnable", _BOOL),
        ("CounterEnable", _BOOL),
        ("CalEnable", _BOOL),
        ("CalDirection", _BOOL),
        ("CalReset", _BOOL),
        ("RangeLimited", _BOOL),
        ("LatchedReset", _BOOL),
        ("PresetReset", _BOOL),
        ("A", _BOOL),
        ("B", _BOOL),
        ("Z", _BOOL),
        ("G", _BOOL),
        ("Calibrated", _BOOL),
        ("Latched", _BOOL),
        ("PresetReached", _BOOL),
    ),
}

for _opaque_name in _OPAQUE_BUILTIN_RECORD_NAMES:
    BUILTIN_RECORD_SPECS[_opaque_name] = ()


BUILTIN_DECLARED_DATATYPE_NAMES = tuple(
    dict.fromkeys([datatype.value for datatype in Simple_DataType] + list(BUILTIN_RECORD_SPECS))
)
