from __future__ import annotations

from ._builtin_datatypes_shared import (
    BOOL as _BOOL,
)
from ._builtin_datatypes_shared import (
    DURATION as _DURATION,
)
from ._builtin_datatypes_shared import (
    IDENT as _IDENT,
)
from ._builtin_datatypes_shared import (
    INT as _INT,
)
from ._builtin_datatypes_shared import (
    LINE as _LINE,
)
from ._builtin_datatypes_shared import (
    MAX as _MAX,
)
from ._builtin_datatypes_shared import (
    REAL as _REAL,
)
from ._builtin_datatypes_shared import (
    STATIC_FUNCTION_POINT_FIELDS as _STATIC_FUNCTION_POINT_FIELDS,
)
from ._builtin_datatypes_shared import (
    STATIC_FUNCTION_USED_FIELDS as _STATIC_FUNCTION_USED_FIELDS,
)
from ._builtin_datatypes_shared import (
    STR as _STR,
)
from ._builtin_datatypes_shared import (
    TAG as _TAG,
)
from ._builtin_datatypes_shared import (
    TIME as _TIME,
)
from ._builtin_datatypes_shared import (
    BuiltinFieldSpec,
)

BUILTIN_RECORD_SPECS_PART2: dict[str, tuple[BuiltinFieldSpec, ...]] = {
    "RelayPidTunerPar": (
        ("Gain", _REAL),
        ("Gain2", _REAL),
        ("Gain3", _REAL),
        ("Gain4", _REAL),
        ("Ti", _REAL),
        ("Ti2", _REAL),
        ("Ti3", _REAL),
        ("Ti4", _REAL),
        ("Td", _REAL),
        ("Td2", _REAL),
        ("Td3", _REAL),
        ("Td4", _REAL),
        ("Lim1", _REAL),
        ("Lim2", _REAL),
        ("Lim3", _REAL),
        ("DeadTime", _REAL),
        ("Bias", _REAL),
        ("Dz", _REAL),
        ("Direct", _BOOL),
        ("Integral", _BOOL),
        ("FeedForwardGain", _REAL),
        ("SpMax", _REAL),
        ("SpMin", _REAL),
        ("LimitOutput", _BOOL),
        ("CMaxLimit", _REAL),
        ("CMinLimit", _REAL),
        ("CIncSpeed", _REAL),
        ("CDecSpeed", _REAL),
        ("SpManualValue", _REAL),
        ("External", _BOOL),
        ("CManualValue", _REAL),
        ("Automatic", _BOOL),
        ("Tune", _BOOL),
        ("DirectKnown", _BOOL),
        ("Reset", _BOOL),
        ("MaxRelay", _REAL),
        ("RegDes", _INT),
        ("RegDesSpeed", _INT),
        ("DesignIsNormal", _BOOL),
        ("DesignIsPI", _BOOL),
        ("DesignIsDeadtime", _BOOL),
        ("DesignSpeedNormal", _BOOL),
        ("DesignSpeedFast", _BOOL),
        ("DesignSpeedSlow", _BOOL),
        ("ReDesign", _BOOL),
        ("Message", _INT),
        ("GSref", _REAL),
        ("GSvariable", _INT),
        ("GSrefIsC", _BOOL),
        ("GSrefIsPv", _BOOL),
        ("GSrefIsSp", _BOOL),
        ("GSrefIsExt", _BOOL),
        ("Set1", _BOOL),
        ("Set2", _BOOL),
        ("Set3", _BOOL),
        ("Set4", _BOOL),
        ("UseSet2", _BOOL),
        ("UseSet3", _BOOL),
        ("UseSet4", _BOOL),
        ("TunerGain", _REAL),
        ("TunerTi", _REAL),
        ("TunerTd", _REAL),
        ("TunerPidParValid", _BOOL),
        ("LoadTunerPar", _BOOL),
        ("NotLoadTunerPar", _BOOL),
        ("MaxSamp", _REAL),
        ("MaxSampValid", _BOOL),
        ("OscillationDetection", _BOOL),
    ),
    "SAPar": (
        ("Enable_Analyze", _BOOL),
        ("Reset", _BOOL),
        ("Freq1", _REAL),
        ("Freq2", _REAL),
        ("Freq3", _REAL),
        ("Freq4", _REAL),
        ("Freq5", _REAL),
        ("Freq6", _REAL),
        ("Freq7", _REAL),
        ("MaxEnergy", _REAL),
        ("MaxFreq", _REAL),
        ("HalfFreq", _REAL),
        ("IncFreq", _BOOL),
        ("DecFreq", _BOOL),
        ("FreqFactor", _INT),
        ("AdaptRate", _INT),
        ("Filt_TimeConstant", _REAL),
        ("Filt_Percentage", _REAL),
        ("Filt_FreqMin", _REAL),
        ("Filt_DisplayInfo", _BOOL),
        ("TotalTime", _REAL),
        ("ElapsedTime", _REAL),
        ("Warning", _BOOL),
        ("Signal_StandDev", _REAL),
        ("StartOnManualChange", _BOOL),
        ("StopOnStationary", _BOOL),
        ("WindowDisplayed", _BOOL),
        ("TimeElapsed", _STR),
        ("Time", _DURATION),
    ),
    "SelectorChain": (
        ("Number", _INT),
        ("ProposedNb", _INT),
        ("SelectedNb", _INT),
        ("Signal", "RealSignal"),
    ),
    "SplitRangeRealSPar": (
        ("imin1", _REAL),
        ("imax1", _REAL),
        ("omin1", _REAL),
        ("omax1", _REAL),
        ("imin2", _REAL),
        ("imax2", _REAL),
        ("omin2", _REAL),
        ("omax2", _REAL),
    ),
    "SqrtRealSPar": (
        ("Gain", _REAL),
        ("Bias", _REAL),
        ("Linear", _REAL),
    ),
    "StaticFunctionRSPar": (
        ("Bias", _REAL),
        ("x1", _REAL),
        ("y1", _REAL),
        ("x2", _REAL),
        ("y2", _REAL),
        *_STATIC_FUNCTION_POINT_FIELDS,
        *_STATIC_FUNCTION_USED_FIELDS,
    ),
    "StictionCompRealSPar": (
        ("EnableStictionComp", _BOOL),
        ("PulseAmplitude", _REAL),
        ("PulseWidth", _REAL),
        ("PulsePeriodFactor", _INT),
    ),
    "TestPar": (
        ("Step_Prompt", _BOOL),
        ("Step_PosAnswer", _BOOL),
        ("Step_NegAnswer", _BOOL),
        ("HystFric_Prompt", _BOOL),
        ("HystFric_PosAnswer", _BOOL),
        ("HystFric_NegAnswer", _BOOL),
        ("FrictionAccuracy", _INT),
        ("Ramp_Back", _BOOL),
        ("PvMax", _REAL),
        ("PvMin", _REAL),
        ("ElapsedTime", _REAL),
        ("TotalTime", _REAL),
        ("DeadTime", _REAL),
        ("StaticGain", _REAL),
        ("TimeConstant", _REAL),
        ("Friction", _REAL),
        ("Hysteresis", _REAL),
        ("TestInProgress", _BOOL),
        ("Status", _INT),
        ("Warning", _INT),
        ("ForcedBack", _BOOL),
        ("DurationChanged", _BOOL),
    ),
    "EventConnection": (
        ("Condition", _BOOL),
        ("Status", _INT),
    ),
    "LoggedEvent": (
        ("FormattedInfo", _MAX),
        ("Id", "LoggedEventKey"),
        ("Description", _LINE),
        ("Data", _LINE),
        ("DataOld", _LINE),
    ),
    "LoggedEventKey": (
        ("objecttag", _TAG),
        ("user", _IDENT),
        ("severity", _INT),
        ("class", _INT),
        ("alon", _BOOL),
        ("aloff", _BOOL),
        ("ack", _BOOL),
        ("inh", _BOOL),
        ("caninh", _BOOL),
        ("autoinh", _BOOL),
        ("autoinhoff", _BOOL),
        ("opinteract", _BOOL),
    ),
    "CurveRealSData": (
        ("PathSuffix", _STR),
        ("PathPrefix", _STR),
    ),
    "JournalAttributes": (
        ("deletable", _BOOL),
        ("overwrite", _BOOL),
        ("autonewentry", _BOOL),
    ),
    "ComliAlarmTxtType": (
        ("Status", _INT),
        ("IOAddress", _INT),
        ("AckAddress", _INT),
        ("Time", _TIME),
        ("AlarmText", _LINE),
    ),
    "ComliAlarmackType": (
        ("IOAddress", _INT),
        ("AckAddress", _INT),
    ),
    "VarGroupType": (
        ("GroupRef", "tObject"),
        ("RemoteError", _BOOL),
        ("GroupIsDefined", _BOOL),
    ),
}
