# pyright: reportUnsupportedDunderAll=false
"""Developer tooling for analysis and validation workflows."""

from __future__ import annotations

from . import (
    _ai_chat_grounding,
    _ai_chat_transcripts,
    _portable_command_text,
    _semble_adapter,
    accuracy_metrics,
    ai,
    ai_chat_observability,
    ai_templates,
    ai_work_map,
    artifact_readiness,
    artifact_registry,
    audit,
    audit_core,
    audit_core_discovery,
    audit_orchestration,
    baselines,
    compare_audit_findings,
    coordination_lock_state,
    corpus,
    coverage_reports,
    derived_reports,
    differential,
    doc_gardener,
    fault_injection,
    finding_exports,
    layer_linter,
    leak_detection,
    leak_detection_scan_paths,
    ledger,
    mutation_engine,
    observability,
    parser_properties,
    pipeline,
    production_summary,
    profiler,
    property_tests,
    refactoring,
    release_smoke,
    repo_audit,
    repo_audit_cli,
    repo_audit_entrypoints,
    review_tool,
    sandbox,
    source_diff_report,
    structural_reports,
    trace_reports,
)
from .accuracy_metrics import (
    VALIDATION_ANNOTATIONS_FILENAME,
    AccuracyMetrics,
    ValidationAnnotation,
    build_accuracy_metrics,
    load_annotations,
    write_accuracy_metrics,
)
from .ai import ai_gc
from .artifact_registry import (
    ACCURACY_METRICS_FILENAME,
    ACCURACY_SCHEMA_KIND,
    ACCURACY_SCHEMA_VERSION,
    ANALYSIS_DIFF_SCHEMA_KIND,
    ANALYSIS_DIFF_SCHEMA_VERSION,
    AUDIT_ARTIFACTS,
    CORPUS_RESULTS_FILENAME,
    CORPUS_RESULTS_SCHEMA_KIND,
    CORPUS_RESULTS_SCHEMA_VERSION,
    FAULT_INJECTION_RESULTS_FILENAME,
    FAULT_INJECTION_SCHEMA_KIND,
    FAULT_INJECTION_SCHEMA_VERSION,
    FUZZER_REPORT_FILENAME,
    FUZZER_REPORT_SCHEMA_KIND,
    FUZZER_REPORT_SCHEMA_VERSION,
    PIPELINE_ARTIFACTS,
    PROPERTY_TEST_RESULTS_FILENAME,
    PROPERTY_TEST_SCHEMA_KIND,
    PROPERTY_TEST_SCHEMA_VERSION,
    ArtifactDefinition,
)
from .audit import _repo_audit_full_run, repo_audit_cli_reporting, repo_audit_compat, repo_audit_runs, repo_audit_shared
from .baselines import build_analysis_diff_report, load_finding_collection
from .corpus import (
    CorpusCaseManifest,
    CorpusEvaluation,
    CorpusExpectation,
    CorpusRunResult,
    CorpusSuiteResult,
    execute_corpus_case,
    run_corpus_case,
    run_corpus_suite,
)
from .doc_gardener import DocFinding, run_scan
from .fault_injection import (
    FaultInjectionResults,
    FaultInjector,
    FaultRunRecord,
    FaultSpec,
    run_fault_injection_campaign,
    write_fault_injection_results,
)
from .observability import collect_all_metrics, read_metrics, write_metrics
from .pipeline import (
    _pipeline_cli,
    _pipeline_execution,
    _pipeline_failure_outputs,
    _pipeline_finish_gate,
    _pipeline_optional_reports_helpers,
    _pipeline_parsing_helpers,
    _pipeline_status_assembly,
)
from .property_tests import (
    PropertyCheckRecord,
    PropertyTestResults,
    generate_seeded_property_inputs,
    run_property_tests,
    write_property_test_results,
)
from .review_tool import print_review, run_full_review
from .sandbox import FUZZER_DEFAULT_TIMEOUT_SECONDS, fuzzer
from .sandbox.fuzzer import (
    FuzzerReport,
    FuzzExecutionRecord,
    FuzzTarget,
    build_seed_corpus,
    parser_fuzz_target,
    run_fuzz_target,
    run_parser_fuzzer,
    write_fuzzer_report,
)
from .sandbox.fuzzer import (
    analyze_fuzz_crashes as analyze_crashes,
)
from .shared import pipeline_artifacts, pipeline_checks
from .structural import _structural_budget_inventory, impact_analyzer, metrics_dashboard

__all__ = (
    "ACCURACY_METRICS_FILENAME",
    "ACCURACY_SCHEMA_KIND",
    "ACCURACY_SCHEMA_VERSION",
    "ANALYSIS_DIFF_SCHEMA_KIND",
    "ANALYSIS_DIFF_SCHEMA_VERSION",
    "AUDIT_ARTIFACTS",
    "CORPUS_RESULTS_FILENAME",
    "CORPUS_RESULTS_SCHEMA_KIND",
    "CORPUS_RESULTS_SCHEMA_VERSION",
    "FAULT_INJECTION_RESULTS_FILENAME",
    "FAULT_INJECTION_SCHEMA_KIND",
    "FAULT_INJECTION_SCHEMA_VERSION",
    "FUZZER_DEFAULT_TIMEOUT_SECONDS",
    "FUZZER_REPORT_FILENAME",
    "FUZZER_REPORT_SCHEMA_KIND",
    "FUZZER_REPORT_SCHEMA_VERSION",
    "PIPELINE_ARTIFACTS",
    "PROPERTY_TEST_RESULTS_FILENAME",
    "PROPERTY_TEST_SCHEMA_KIND",
    "PROPERTY_TEST_SCHEMA_VERSION",
    "VALIDATION_ANNOTATIONS_FILENAME",
    "AccuracyMetrics",
    "ArtifactDefinition",
    "CorpusCaseManifest",
    "CorpusEvaluation",
    "CorpusExpectation",
    "CorpusRunResult",
    "CorpusSuiteResult",
    "DocFinding",
    "FaultInjectionResults",
    "FaultInjector",
    "FaultRunRecord",
    "FaultSpec",
    "FuzzExecutionRecord",
    "FuzzTarget",
    "FuzzerReport",
    "PropertyCheckRecord",
    "PropertyTestResults",
    "ValidationAnnotation",
    "accuracy_metrics",
    "ai_chat_observability",
    "ai_gc",
    "ai_templates",
    "ai_work_map",
    "analyze_crashes",
    "artifact_readiness",
    "artifact_registry",
    "audit_core",
    "audit_core_discovery",
    "audit_orchestration",
    "baselines",
    "build_accuracy_metrics",
    "build_analysis_diff_report",
    "build_seed_corpus",
    "collect_all_metrics",
    "compare_audit_findings",
    "coordination_lock_state",
    "corpus",
    "coverage_reports",
    "derived_reports",
    "differential",
    "doc_gardener",
    "execute_corpus_case",
    "fault_injection",
    "finding_exports",
    "fuzzer",
    "generate_seeded_property_inputs",
    "impact_analyzer",
    "layer_linter",
    "leak_detection",
    "leak_detection_scan_paths",
    "ledger",
    "load_annotations",
    "load_finding_collection",
    "metrics_dashboard",
    "mutation_engine",
    "observability",
    "parser_fuzz_target",
    "parser_properties",
    "pipeline",
    "pipeline_artifacts",
    "pipeline_checks",
    "print_review",
    "production_summary",
    "profiler",
    "property_tests",
    "read_metrics",
    "refactoring",
    "release_smoke",
    "repo_audit",
    "repo_audit_cli",
    "repo_audit_cli_reporting",
    "repo_audit_compat",
    "repo_audit_entrypoints",
    "repo_audit_runs",
    "repo_audit_shared",
    "review_tool",
    "run_corpus_case",
    "run_corpus_suite",
    "run_fault_injection_campaign",
    "run_full_review",
    "run_fuzz_target",
    "run_parser_fuzzer",
    "run_property_tests",
    "run_scan",
    "source_diff_report",
    "structural_reports",
    "trace_reports",
    "write_accuracy_metrics",
    "write_fault_injection_results",
    "write_fuzzer_report",
    "write_metrics",
    "write_property_test_results",
)
