from __future__ import annotations

from docx.document import Document as DocClass

from ..classification import DocumentationClassification, DocumentedModule
from ._core import DocumentUnit, _bullet, _centered_title, _heading, _paragraph, _prettify_name, _table, _underlined
from ._data_helpers import (
    _calculation_rows,
    _communication_rows,
    _configurable_parameter_rows,
    _entry_variable_text,
    _event_table_rows,
    _exception_rows,
    _first_non_empty,
    _generic_section_rows,
    _interlock_rows,
    _is_calculation_entry,
    _is_cip_valve_entry,
    _is_event_entry,
    _is_graphics_entry,
    _is_inlet_consumption_entry,
    _is_intervention_entry,
    _is_measurement_entry,
    _is_other_device_entry,
    _is_special_logging_entry,
    _is_supervision_entry,
    _is_timer_entry,
    _measurement_rows,
    _metadata_value,
    _module_description,
    _module_list_rows,
    _module_title,
    _moduletype_summary,
    _parameter_catalog_rows,
    _pid_controller_rows,
    _simple_name_tag_rows,
    _state_rows,
    _support_entries,
    _variable_rows,
)


def _render_named_table_section(
    doc: DocClass,
    title: str,
    rows: list[list[str]],
    *,
    headers: list[str],
    level: int = 3,
    widths: tuple[int, ...] = (),
    empty_text: str = "N/A",
) -> None:
    _heading(doc, title, level=level)
    if not rows:
        _paragraph(doc, empty_text, style="Body Text")
        return
    _table(doc, headers, rows, col_widths=widths)


def _render_document_cover(
    doc: DocClass, classification: DocumentationClassification, units: list[DocumentUnit]
) -> None:
    _centered_title(doc, "Functional Specification")
    scope_units = ", ".join(unit.unit_code for unit in units) or "All detected units"
    _paragraph(doc, f"Generated from source code for {scope_units}.")
    _table(doc, ["NNE Author", "NNE Author", "NNE Author"], [["Generated by SattLint", "", ""]], col_widths=(2, 2, 2))
    _table(doc, ["", "Document", "NN Doc. no."], [["", "Functional Specification", scope_units]], col_widths=(1, 3, 2))
    doc.add_page_break()


def _render_introduction(doc: DocClass, units: list[DocumentUnit]) -> None:
    _heading(doc, "Introduction", level=1)
    _heading(doc, "Scope", level=2)
    _paragraph(
        doc,
        "This document is the generated Functional Specification (FS) for the detected process units and their configured physical and procedural elements.",
    )
    if units:
        _paragraph(doc, "The FS covers the following detected units:")
        for unit in units:
            _bullet(doc, f"{unit.unit_code} {unit.title}")
    _heading(doc, "S88 Model", level=2)
    _paragraph(doc, "The ANSI/ISA-88 (S88) model is used to structure the generated specification.")
    _underlined(doc, "S88 Physical Model")
    _paragraph(
        doc,
        "The physical model section groups units, equipment modules, device interfaces, and communication links detected from the source structure.",
    )
    _underlined(doc, "S88 Procedural Model")
    _paragraph(
        doc,
        "The procedural model section groups detected operations together with their parameters, messages, events, and available sequence logic.",
    )
    _heading(doc, "Definitions and abbreviations", level=2)
    _heading(doc, "Abbreviations", level=3)
    for abbreviation, meaning in (
        ("EM", "Equipment Module"),
        ("EP", "Engineering Parameter"),
        ("FS", "Functional Specification"),
        ("OP", "Operation"),
        ("RP", "Recipe Parameter"),
        ("UP", "User Parameter"),
    ):
        _paragraph(doc, f"{abbreviation} {meaning}")


def _render_references(doc: DocClass, classification: DocumentationClassification, units: list[DocumentUnit]) -> None:
    _heading(doc, "References", level=2)
    _bullet(doc, f"Detected units: {len(units)}")
    _bullet(doc, f"Equipment modules: {sum(len(unit.equipment_modules) for unit in units)}")
    _bullet(doc, f"Operations: {sum(len(unit.operations) for unit in units)}")
    _bullet(doc, f"Recipe parameters: {sum(len(unit.recipe_parameters) for unit in units)}")
    _bullet(doc, f"Engineering parameters: {sum(len(unit.engineering_parameters) for unit in units)}")
    _bullet(doc, f"Uncategorized modules: {len(classification.uncategorized)}")


def _render_physical_model(
    doc: DocClass, units: list[DocumentUnit], classification: DocumentationClassification
) -> None:
    _heading(doc, "S88 Physical model", level=1)
    process_cell_name = (
        ", ".join(sorted({unit.section_name for unit in units if unit.section_name})) or "Detected process cell"
    )
    _heading(doc, f"Process Cell - {process_cell_name}", level=2)
    _paragraph(doc, "The detected process cell comprises the units listed below.")
    _table(
        doc,
        ["Unit", "Unit Class", "Danish Description", "Unit Definition"],
        [[unit.unit_code, unit.unit_class, unit.title, f"See section {unit.title}"] for unit in units],
        col_widths=(1, 2, 2, 2),
    )
    _render_named_table_section(
        doc,
        "Instance-configurable parameters",
        [row for unit in units for row in _configurable_parameter_rows(unit)],
        headers=["Unit Parameter", "Description", "Unit Instance", "Configured to"],
        level=3,
        widths=(2, 3, 1, 2),
    )
    for index, unit in enumerate(units, start=1):
        _render_unit_physical_section(doc, unit, classification, index=index)


def _render_unit_physical_section(
    doc: DocClass, unit: DocumentUnit, classification: DocumentationClassification, *, index: int
) -> None:
    support_entries = _support_entries(unit, classification)
    _heading(doc, f"Unit Class definition: {unit.title}", level=2)
    _paragraph(
        doc, f"This section summarizes the detected physical structure for unit {unit.unit_code}.", style="Body Text"
    )
    _paragraph(doc, f"Overall detected unit class: {_prettify_name(unit.unit_class)}.", style="Caption")
    _paragraph(
        doc,
        "Note: The generated section is based on code structure, parameter mappings, and detected module groupings.",
    )
    _render_named_table_section(
        doc,
        "Equipment module instances",
        _module_list_rows(unit.equipment_modules),
        headers=["Equipment Module Name", "Description", "Definition"],
        level=3,
        widths=(2, 3, 2),
    )
    _render_named_table_section(
        doc,
        "Measurements and logging",
        _measurement_rows([entry for entry in support_entries if _is_measurement_entry(entry)]),
        headers=[
            "Measurement",
            "Tag",
            "Min",
            "Max",
            "Eng. Unit",
            "Log interval\n(Max)",
            "Dead-band\nrelative",
            "Log interval \n(Min)",
        ],
        level=3,
        widths=(2, 1, 1, 1, 1, 1, 1, 1),
    )
    _render_named_table_section(
        doc,
        "Special Logging",
        [
            [
                _module_description(entry),
                entry.name,
                _entry_variable_text(entry, "min", "lowlimit"),
                _entry_variable_text(entry, "max", "highlimit"),
                _first_non_empty(
                    _metadata_value(entry, "EngUnit", "Unit"), _entry_variable_text(entry, "engunit", "unit")
                ),
            ]
            for entry in support_entries
            if _is_special_logging_entry(entry)
        ],
        headers=["Log description", "Tag", "Min", "Max", "Eng. Unit"],
        level=3,
        widths=(3, 1, 1, 1, 1),
    )
    _render_named_table_section(
        doc,
        "Inlet Consumption Logging",
        [
            [
                _moduletype_summary(entry),
                _module_description(entry),
                entry.name,
                _metadata_value(entry, "Format"),
                _metadata_value(entry, "Measurement"),
                _first_non_empty(_metadata_value(entry, "Enabled"), "Yes"),
            ]
            for entry in support_entries
            if _is_inlet_consumption_entry(entry)
        ],
        headers=["Journal Type", "Description", "Log Parameter Name", "Format", "Measurement", "Enabled"],
        level=3,
        widths=(2, 3, 2, 1, 1, 1),
    )
    _render_named_table_section(
        doc,
        "Other Devices",
        _simple_name_tag_rows([entry for entry in support_entries if _is_other_device_entry(entry)], "description"),
        headers=["Device Description", "Tag"],
        level=3,
        widths=(4, 2),
    )
    _render_named_table_section(
        doc,
        "Timers",
        [
            [
                entry.name,
                _module_description(entry),
                _metadata_value(entry, "Operation"),
                _metadata_value(entry, "Operation2"),
            ]
            for entry in support_entries
            if _is_timer_entry(entry)
        ],
        headers=["Timer", "Description", "Operation", "Operation"],
        level=3,
        widths=(2, 3, 1, 1),
    )
    _render_named_table_section(
        doc,
        "Unit Events",
        _event_table_rows([entry for entry in support_entries if _is_event_entry(entry)]),
        headers=["Tag", "Event Text", "Sev.", "Activation"],
        level=3,
        widths=(2, 3, 1, 2),
    )
    _render_named_table_section(
        doc,
        "Interlocks",
        _interlock_rows([variable for variable in unit.root.localvariables if "interlock" in variable.name.casefold()]),
        headers=[
            "Tag",
            "Description",
            "Interlock Activation\n(Condition to cause interlock)",
            "Interlock Enable\n(Manipulation of equipment)",
        ],
        level=3,
        widths=(2, 2, 2, 2),
    )
    _render_named_table_section(
        doc,
        "Interventions",
        _generic_section_rows([entry for entry in support_entries if _is_intervention_entry(entry)]),
        headers=["Name", "Module Type", "Location", "Notes"],
        level=3,
        widths=(2, 2, 3, 2),
    )
    _render_named_table_section(
        doc,
        "Exceptions",
        _exception_rows(
            [variable for variable in unit.root.moduleparameters if variable.name.casefold().startswith("error_")]
        ),
        headers=["Condition", "Exceptions Description"],
        level=3,
        widths=(2, 4),
    )
    _render_named_table_section(
        doc,
        "Supervision",
        _generic_section_rows([entry for entry in support_entries if _is_supervision_entry(entry)]),
        headers=["Name", "Module Type", "Location", "Notes"],
        level=3,
        widths=(2, 2, 3, 2),
    )
    _render_named_table_section(
        doc,
        "Unit graphics",
        _generic_section_rows([entry for entry in support_entries if _is_graphics_entry(entry)]),
        headers=["Name", "Module Type", "Location", "Notes"],
        level=3,
        widths=(2, 2, 3, 2),
    )
    _render_named_table_section(
        doc,
        "CIP Flip of valves",
        _generic_section_rows([entry for entry in support_entries if _is_cip_valve_entry(entry)]),
        headers=["Name", "Module Type", "Location", "Notes"],
        level=3,
        widths=(2, 2, 3, 2),
    )
    _render_named_table_section(
        doc,
        "Calculations",
        _calculation_rows([entry for entry in support_entries if _is_calculation_entry(entry)]),
        headers=["Tag", "Description", "Calculation"],
        level=3,
        widths=(2, 3, 2),
    )
    _heading(doc, "Communication", level=3)
    from_rows = _communication_rows(unit, direction="from")
    to_rows = _communication_rows(unit, direction="to")
    if from_rows:
        _table(doc, ["From", "Comment"], from_rows, col_widths=(2, 4))
    else:
        _paragraph(doc, "N/A", style="Body Text")
    if to_rows:
        _table(doc, ["To", "Comment"], to_rows, col_widths=(2, 4))
    for equipment_module in unit.equipment_modules:
        _render_equipment_module_section(doc, equipment_module, classification)


def _render_equipment_module_section(
    doc: DocClass, entry: DocumentedModule, classification: DocumentationClassification
) -> None:
    _heading(doc, f"Equipment Module {_module_title(entry)}", level=3)
    _underlined(doc, "Description")
    _paragraph(doc, _module_description(entry))
    _render_named_table_section(
        doc,
        "States",
        _state_rows(entry, classification),
        headers=["State", "Description", "Logic"],
        level=4,
        widths=(2, 3, 2),
    )
    parameter_entries = classification.descendants(entry, category="ep")
    parameter_rows = _parameter_catalog_rows(parameter_entries)
    if not parameter_rows:
        parameter_rows = _variable_rows(
            [
                variable
                for variable in (*entry.moduleparameters, *entry.localvariables)
                if variable.name.casefold() not in {"name", "p", "colours"}
            ]
        )
        _render_named_table_section(
            doc,
            "Parameters",
            parameter_rows,
            headers=["Tag", "Datatype", "Init", "Description"],
            level=4,
            widths=(2, 2, 1, 3),
        )
    else:
        _render_named_table_section(
            doc,
            "Parameters",
            parameter_rows,
            headers=["Parameter", "Module Type", "Location", "Description"],
            level=4,
            widths=(2, 2, 3, 2),
        )
    _render_named_table_section(
        doc,
        "PID Controllers",
        _pid_controller_rows(entry, classification),
        headers=["Tag", "Module Type", "Location", "Description"],
        level=4,
        widths=(2, 2, 3, 2),
    )
