name: ClusterFuzzLite

on:
  schedule:
    - cron: "27 3 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fuzzing:
    name: Fuzzing
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          persist-credentials: false

      - name: Run ClusterFuzzLite
        uses: google/clusterfuzzlite@52ecc61cb587ee99c26825a112a21abf19c7448c
        with:
          output-sarif: true
